<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Error_InvalidUnPw</name>
   <tag></tag>
   <elementGuidId>0d106aef-ba03-411a-8404-de07b5bbaa62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginMessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginMessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4ec640a9-2aea-4107-be21-02f18c8d08f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginMessage</value>
      <webElementGuid>3d08f27b-6964-4453-aada-425623f8fd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-danger</value>
      <webElementGuid>4215e6ca-1382-4938-8caa-bf14318eab36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The username or password you entered is incorrect.</value>
      <webElementGuid>d261a717-a6e0-4c8f-aff7-87342cc50e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginMessage&quot;)</value>
      <webElementGuid>c1dded2c-4691-4c35-b37a-ebc12bad79a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='loginMessage']</value>
      <webElementGuid>9f891392-b9ca-4fe0-a59a-23e46c607e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div/div</value>
      <webElementGuid>d472a7dd-19cc-4086-81a4-6515af8d1c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::div[2]</value>
      <webElementGuid>c6dc7d3e-4305-4331-aff7-d4e0500eb675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User name'])[1]/preceding::div[1]</value>
      <webElementGuid>deee8701-86d8-462b-b014-22a19088f8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::div[3]</value>
      <webElementGuid>1b52b07a-6c8e-4c65-91b5-ad9786c97364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The username or password you entered is incorrect.']/parent::*</value>
      <webElementGuid>935b009e-e3b9-4ea4-8795-4658f88b51c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>5c6ed1b7-8466-40ee-8b5b-cc53f0a8004a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'loginMessage' and (text() = 'The username or password you entered is incorrect.' or . = 'The username or password you entered is incorrect.')]</value>
      <webElementGuid>3ff3d274-9d10-44ea-93b2-fd233614b047</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
