<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit request</name>
   <tag></tag>
   <elementGuidId>72ce0a7f-a6b8-49d1-af03-34f83626ebd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[text()='Submit request']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.mx-button.mx-name-actionButton1.pull-right.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>72a856ff-8e64-4432-ad77-716db9bdbc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bbe6e065-9456-4f41-a1f8-8859a5ce2f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mx-button mx-name-actionButton1 pull-right btn-primary</value>
      <webElementGuid>f2e1610a-88a0-4128-8e2e-2f420e087ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-id</name>
      <type>Main</type>
      <value>10.LeaveRequest.LeaveRequest_New.actionButton1</value>
      <webElementGuid>176694d0-9203-45a7-8fcd-6808cba7d454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4da4117c-d2af-4d65-8f7a-7d0633abf6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Submit request</value>
      <webElementGuid>3fa4d036-6b35-4956-b917-096ed890650e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mxui_widget_DataView_6&quot;)/div[@class=&quot;mx-dataview-content&quot;]/div[@class=&quot;mx-layoutgrid mx-layoutgrid-fixed container mx-name-layoutGrid1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-md-9 col-auto card&quot;]/div[@class=&quot;mx-name-container10 row-right&quot;]/button[@class=&quot;btn mx-button mx-name-actionButton1 pull-right btn-primary&quot;]</value>
      <webElementGuid>fcea8689-978c-4393-992a-442336c006a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>90aeabe4-09aa-4fe7-9bb3-fbb790c8ae38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mxui_widget_DataView_6']/div/div/div[2]/div/div[5]/button[2]</value>
      <webElementGuid>6e68f7d8-e37c-442f-a75d-8114a2041bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note (optional)'])[1]/following::button[2]</value>
      <webElementGuid>3c6091e6-0c27-4708-b917-5f60c6efb283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick info'])[1]/preceding::button[1]</value>
      <webElementGuid>aa5ff577-dcac-4519-9245-be1dbcc3e8dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available PTO'])[1]/preceding::button[1]</value>
      <webElementGuid>4462ab12-e452-442d-a88f-2459d9503b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit request']/parent::*</value>
      <webElementGuid>5173d357-4b03-4d25-a87f-6a1d1990f62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>5ede6a0f-270a-43e4-a7c8-0113fd062452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Submit request' or . = ' Submit request')]</value>
      <webElementGuid>42db9c5c-05c8-4c89-9b83-324e2856456d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
