<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a leave typeSpecial leavePart_b985c2</name>
   <tag></tag>
   <elementGuidId>d476d8fd-5f5d-42dc-85ac-85783651362c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave type'])[1]/following::select[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a9e060e4-d02c-4594-add7-321291600b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>10.LeaveRequest.LeaveRequest_New.dropDown1_krt_136</value>
      <webElementGuid>339f1548-afa4-4cc0-b809-4e8c05219c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ec5cae54-51f7-473d-acf9-44359e7ac5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a leave typeSpecial leavePartner leavePaid time offParental leaveSick leave</value>
      <webElementGuid>f46edf7d-862c-45f0-b50c-9b33a6fd491d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;10.LeaveRequest.LeaveRequest_New.dropDown1_krt_136&quot;)</value>
      <webElementGuid>279bab6c-00a4-4f09-b81d-8276960224f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='10.LeaveRequest.LeaveRequest_New.dropDown1_krt_136']</value>
      <webElementGuid>ea5bc96c-81b5-4456-bcef-1105b075ed3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mxui_widget_DataView_6']/div/div/div[2]/div/div[2]/select</value>
      <webElementGuid>7f53976f-9157-4d1b-b928-014e7d3e0f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave type'])[1]/following::select[1]</value>
      <webElementGuid>5bb359b5-3d08-4ccb-8532-e6a404653a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::select[1]</value>
      <webElementGuid>9ad44c84-6dc5-4542-918f-e8219bc19155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/preceding::select[1]</value>
      <webElementGuid>2c25f788-0952-4dba-bf66-023f42f8a79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri, Aug 12'])[1]/preceding::select[1]</value>
      <webElementGuid>1615d5a4-1db3-474d-b508-f198b37eaa0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>5768ed69-63c8-4c34-9e02-f53363c84f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '10.LeaveRequest.LeaveRequest_New.dropDown1_krt_136' and (text() = 'Select a leave typeSpecial leavePartner leavePaid time offParental leaveSick leave' or . = 'Select a leave typeSpecial leavePartner leavePaid time offParental leaveSick leave')]</value>
      <webElementGuid>5cccb779-7cce-4982-8e74-4b993133fb9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
