<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit in Studio Pro</name>
   <tag></tag>
   <elementGuidId>3eb94f88-883f-4661-88ff-60907e83c17c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mxui_widget_Wrapper_43</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mxui_widget_Wrapper_43']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>962a3fd8-3a90-41c2-abc4-0359eee94257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dc1ce079-b755-4d7c-8409-bd155f737f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mxui_widget_Wrapper_43</value>
      <webElementGuid>3d0e97a7-a1a7-4faf-b678-214754db2ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mx-button mx-name-edit_in_studio_pro_button pds-c-button--text btn-default mx-focus</value>
      <webElementGuid>be99608f-3a99-41a5-95a5-d4534b88257e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>911f9164-d9a7-4f73-9d88-37309ff7b015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mendix-id</name>
      <type>Main</type>
      <value>52_27_30</value>
      <webElementGuid>8114f4bb-f120-4a67-9752-9cd766b98a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>widgetid</name>
      <type>Main</type>
      <value>mxui_widget_Wrapper_43</value>
      <webElementGuid>14eda50a-a5ab-4f1e-a454-07a12cff27d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Edit in Studio Pro</value>
      <webElementGuid>33dbb7fa-9ba4-44d1-8074-8cecc505e206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mxui_widget_Wrapper_43&quot;)</value>
      <webElementGuid>dd86a17b-47ba-41fb-9863-118db4193507</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mxui_widget_Wrapper_43']</value>
      <webElementGuid>5ba0abd5-5e0a-43b6-a43f-be44ceb7e9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mxui_widget_DataView_14']/div/div/button[2]</value>
      <webElementGuid>db3e6427-5a0e-42fc-822e-d262ecd855d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Tracker'])[1]/following::button[2]</value>
      <webElementGuid>40bdcff8-916d-45c6-834d-f241121bba4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View App'])[1]/preceding::button[1]</value>
      <webElementGuid>cc9ba7d1-67ef-4afc-9b0e-de49e1301341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collaborate'])[1]/preceding::button[1]</value>
      <webElementGuid>300f0d94-a28f-4676-9693-cf85fbbebf4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit in Studio Pro']/parent::*</value>
      <webElementGuid>eab77a36-206c-402c-a120-5165e559a018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>80656576-ce63-479d-96ab-3eec1deefb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'mxui_widget_Wrapper_43' and (text() = ' Edit in Studio Pro' or . = ' Edit in Studio Pro')]</value>
      <webElementGuid>68c886c5-b4af-4c5f-995b-dc761255dc09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
