<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit in Studio</name>
   <tag></tag>
   <elementGuidId>7d040420-fc57-473d-82f4-957d0695dc3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mxui_widget_Wrapper_42</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mxui_widget_Wrapper_42']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>646b9e0e-8457-4638-abe8-3bcaeae54180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>18ec922e-ba37-4863-a3dd-d77e5246df1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mxui_widget_Wrapper_42</value>
      <webElementGuid>19e4da09-d094-484e-bf0f-f563fc02127b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mx-button mx-name-edit_in_studio_button pds-c-button--text btn-default mx-focus</value>
      <webElementGuid>839209e7-d4a3-44d7-8da4-5b151b76a23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>63927ae2-db73-4242-9165-c1e7cbcf8491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mendix-id</name>
      <type>Main</type>
      <value>52_27_29</value>
      <webElementGuid>4e3b90cf-5498-4e97-a79b-73c17a801d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>widgetid</name>
      <type>Main</type>
      <value>mxui_widget_Wrapper_42</value>
      <webElementGuid>80a301dd-c51d-4b26-93ff-ec6af070c1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Edit in Studio</value>
      <webElementGuid>46c1c0fa-f5a7-494c-afe4-0e48b6ab2ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mxui_widget_Wrapper_42&quot;)</value>
      <webElementGuid>0ad9315b-6a64-425b-9a86-703045610328</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mxui_widget_Wrapper_42']</value>
      <webElementGuid>9aa270de-1668-4a2a-8097-b1fe54f14a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mxui_widget_DataView_14']/div/div/button</value>
      <webElementGuid>336c13d8-610a-49ad-a754-7fd3ff7b1e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Tracker'])[1]/following::button[1]</value>
      <webElementGuid>06d3adcf-5b84-42da-93e1-e578a59b8597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Apps'])[1]/following::button[5]</value>
      <webElementGuid>d9b506f7-0c55-4393-a38b-4cbdf011f7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View App'])[1]/preceding::button[2]</value>
      <webElementGuid>5527ec53-1c11-4bcc-95f7-d5b68d78b312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit in Studio']/parent::*</value>
      <webElementGuid>ddb55a96-feba-4119-a285-52f10be0d601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/button</value>
      <webElementGuid>fb09870d-e59a-4b48-8d9d-4f55f521aa85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'mxui_widget_Wrapper_42' and (text() = ' Edit in Studio' or . = ' Edit in Studio')]</value>
      <webElementGuid>7c97cbc6-e413-40f0-806a-9cbb928d2c19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
