<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Pinned_mxui_widget_Image_0</name>
   <tag></tag>
   <elementGuidId>35e05b6a-a8a3-40b6-a606-69eaa73864bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='mxui_widget_Image_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mxui_widget_Image_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6c08f269-05dc-4ba8-a5b4-89fcc5f57f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-image mx-name-imageViewer1 pds-c-app-icon pds-c-app-icon--lg pds-u-margin-bottom-16 pds-u-flex-none</value>
      <webElementGuid>3360ee07-9740-4598-aae1-04e0364758b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://sprintr.home.mendix.com/file?guid=23362423068585601&amp;changedDate=1660130269002</value>
      <webElementGuid>1da5db17-0f4b-4b25-8f1f-8fc50056c194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mxui_widget_Image_0</value>
      <webElementGuid>07fd433a-7341-441c-aab5-37019b85444e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mendix-id</name>
      <type>Main</type>
      <value>65_25_28</value>
      <webElementGuid>5414c828-82fa-40aa-8d53-63a62f61fe26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>widgetid</name>
      <type>Main</type>
      <value>mxui_widget_Image_0</value>
      <webElementGuid>7530a77e-0805-416e-ba73-daa05d1aaafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mxui_widget_Image_0&quot;)</value>
      <webElementGuid>436bd0dc-13e6-4b6c-8c52-408b9e57da98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='mxui_widget_Image_0']</value>
      <webElementGuid>3103a4ad-8da3-4060-aef6-088a68e3a367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mxui_widget_DataView_3']/div/div/div/img</value>
      <webElementGuid>8eed7a6f-062d-4f9a-b8e3-aadbcd59f97d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://sprintr.home.mendix.com/file?guid=23362423068585601&amp;changedDate=1660130269002')]</value>
      <webElementGuid>ddd5d7b3-a70a-462a-b4ab-90d828e73ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>0abe2c7d-f04a-497b-9fd7-c2bda7a07f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://sprintr.home.mendix.com/file?guid=23362423068585601&amp;changedDate=1660130269002' and @id = 'mxui_widget_Image_0']</value>
      <webElementGuid>725220d4-6d4c-4afe-9803-5d6bee205272</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
