<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Back to home</name>
   <tag></tag>
   <elementGuidId>36faa603-0a16-4429-8f56-78fa654ac570</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mx-link.mx-name-actionButton3.btn-lg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mxui_widget_VerticalScrollContainer_0']/div[2]/div/div/div/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1bda85a6-1633-4ac2-9e58-219307615277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-link mx-name-actionButton3 btn-lg</value>
      <webElementGuid>b0263042-3fd1-47f2-a3f2-6c5aab31c06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>df061fdc-467f-4d6a-af28-04c302c63bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7d21d06-d6a7-434d-9b33-5b7943b62796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-id</name>
      <type>Main</type>
      <value>7.LeaveRequest.LeaveRequest_Overview.actionButton3</value>
      <webElementGuid>8a83db7c-d23d-46ef-8c55-aac61ccd81b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>170b2774-20e5-4a08-bab4-62f0fb8a82d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> ← Back to home</value>
      <webElementGuid>4c52d554-f59e-4d80-a04b-bc7690a565ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mxui_widget_VerticalScrollContainer_0&quot;)/div[@class=&quot;mx-scrollcontainer-middle region-content&quot;]/div[@class=&quot;mx-scrollcontainer-wrapper&quot;]/div[@class=&quot;mx-placeholder&quot;]/div[@class=&quot;mx-dataview mx-name-dataView1 form-horizontal&quot;]/div[@class=&quot;mx-dataview-content&quot;]/div[@class=&quot;mx-name-layoutGrid1 mx-layoutgrid mx-layoutgrid-fluid container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg col-md col&quot;]/a[@class=&quot;mx-link mx-name-actionButton3 btn-lg&quot;]</value>
      <webElementGuid>0cf1d996-58e6-4419-b042-dcd4abf43221</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mxui_widget_VerticalScrollContainer_0']/div[2]/div/div/div/div/div/div/div/a</value>
      <webElementGuid>9fabc2fd-fcb7-40bd-aded-9d6627632632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My leave requests'])[1]/preceding::a[1]</value>
      <webElementGuid>05cf687f-1ea0-44aa-bf6e-c38a3767a782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='← Back to home']/parent::*</value>
      <webElementGuid>fa666160-abc1-41e2-9866-c865be74c3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[19]</value>
      <webElementGuid>99408b18-eaa3-4775-96f2-83b401d6556d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>1815d044-24e3-4b54-b251-4d21ec09c6d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = ' ← Back to home' or . = ' ← Back to home')]</value>
      <webElementGuid>108c9559-18b8-4e78-8217-9a61657f55f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
