<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel request</name>
   <tag></tag>
   <elementGuidId>e867b93e-66d8-43bb-9340-335d36c66452</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/button[text()='Cancel request']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.mx-button.mx-name-actionButton2.btn-bordered.btn-danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d5a50f1c-affd-492c-8ca0-bec39682dfde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a6fa889-a529-46e2-bdbc-6265295dd983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mx-button mx-name-actionButton2 btn-bordered btn-danger</value>
      <webElementGuid>a75b0958-b7d5-4722-a6d6-8d9cacdc6c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-id</name>
      <type>Main</type>
      <value>7.LeaveRequest.LeaveRequest_Overview.actionButton2</value>
      <webElementGuid>c8b8e0d7-265a-4db4-a292-bc1f5aac2724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0eff1448-84b5-41ca-8806-3ec344e0114b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cancel request</value>
      <webElementGuid>a71c9eb4-7227-4c3b-be2f-cd98a3d076b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mxui_widget_VerticalScrollContainer_0&quot;)/div[@class=&quot;mx-scrollcontainer-middle region-content&quot;]/div[@class=&quot;mx-scrollcontainer-wrapper&quot;]/div[@class=&quot;mx-placeholder&quot;]/div[@class=&quot;mx-dataview mx-name-dataView1 form-horizontal&quot;]/div[@class=&quot;mx-dataview-content&quot;]/div[@class=&quot;mx-name-layoutGrid1 mx-layoutgrid mx-layoutgrid-fluid container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg col-md col&quot;]/div[@class=&quot;mx-name-dataGrid21&quot;]/div[@class=&quot;table&quot;]/div[@class=&quot;table-content&quot;]/div[@class=&quot;tr&quot;]/div[@class=&quot;td align-column-left clickable&quot;]/button[@class=&quot;btn mx-button mx-name-actionButton2 btn-bordered btn-danger&quot;]</value>
      <webElementGuid>560eb3ef-94e0-4ae4-a29d-1a44e714d48f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>4c1171ba-956d-4e2c-ad28-8ca48d698a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mxui_widget_VerticalScrollContainer_0']/div[2]/div/div/div/div/div/div[4]/div/div/div/div[2]/div[10]/div[5]/button</value>
      <webElementGuid>b93ee85f-fb2c-4eaa-a5a6-0b67d98534bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[1]/following::button[1]</value>
      <webElementGuid>5d306255-9cd0-4321-9e0c-38a6e2f029a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On Fri 12 Aug 2022'])[3]/following::button[1]</value>
      <webElementGuid>cfb57765-fe1b-40e5-ae70-8d52668c2a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[5]</value>
      <webElementGuid>5a930652-1d77-4e63-be67-4cc4808b12bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::button[5]</value>
      <webElementGuid>7d326c21-64ea-4235-b995-4b3c6fe8fcad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel request']/parent::*</value>
      <webElementGuid>f5aa65c0-201d-4ca4-af56-28ba24b88dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>4d1f19c7-f52d-4a96-bc35-9368834e4800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Cancel request' or . = ' Cancel request')]</value>
      <webElementGuid>2900b444-21ac-42f9-a597-9f206483a044</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
