<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Home</name>
   <tag></tag>
   <elementGuidId>044a8fa7-5fbb-4d6a-8f5d-6318ec2c1b53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mx-name-menuBar1-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mxui_widget_VerticalScrollContainer_0']/div/div/div[2]/div/div/div/div[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3c828eec-03da-4a00-aaa4-e54595575a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-name-menuBar1-0</value>
      <webElementGuid>cdb9c7b5-7b32-489b-8ff3-8427417a8265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a68fdbe4-be8e-4458-af92-f2847f75494f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>41f222e6-11e2-4bbe-9131-c77db22486c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>a674cd48-a728-4fcf-9d32-ffe6c9d67a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Home</value>
      <webElementGuid>47ff33e3-ffa7-4e20-9db6-87ded24d3404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mxui_widget_VerticalScrollContainer_0&quot;)/div[@class=&quot;mx-scrollcontainer-top region-topbar&quot;]/div[@class=&quot;mx-scrollcontainer-wrapper&quot;]/div[@class=&quot;mx-layoutgrid mx-layoutgrid-fluid container-fluid mx-name-layoutGrid1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-12&quot;]/div[@class=&quot;mx-name-container2 topbar-content&quot;]/div[@class=&quot;navbar navbar-default mx-navbar mx-name-menuBar1 hidden-xs hide-icons&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;mx-navbar-item&quot;]/a[@class=&quot;mx-name-menuBar1-0&quot;]</value>
      <webElementGuid>0517c2b4-3675-4cf5-8f3f-83a6f171aed7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mxui_widget_VerticalScrollContainer_0']/div/div/div[2]/div/div/div/div[2]/ul/li/a</value>
      <webElementGuid>1f6e095c-e309-4d84-bf02-4e8d0e9dc1e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Home')])[2]</value>
      <webElementGuid>979ce114-cf87-44bc-a5ff-02527ca046ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Requests'])[1]/preceding::a[9]</value>
      <webElementGuid>9b8330bb-f96f-4cb7-81ef-ee3cb0a9c88b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='akila.k'])[1]/preceding::a[9]</value>
      <webElementGuid>80be37a7-4a4a-477d-a921-82048df00786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[10]</value>
      <webElementGuid>b65a85d4-a082-4f39-a9a5-75c7af719fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>be9edfd4-aa7e-454e-8acf-c0029d64cd55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Home' and (text() = ' Home' or . = ' Home')]</value>
      <webElementGuid>b852c794-20d2-4ca7-89aa-f5cf272b2efd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
