<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log-out</name>
   <tag></tag>
   <elementGuidId>b4e92df2-77f5-4af5-83f8-5ae79ab5b247</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mx-name-menuBar1-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Log-out')])[2]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#' and @title = 'Log-out' and (text() = ' Log-out' or . = ' Log-out')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b841e4e3-8c55-4509-9f59-d282090ff257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-name-menuBar1-6</value>
      <webElementGuid>8a71cf25-5733-490e-a52a-b6a6ea6de615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2a17133a-b739-4fa7-87c8-28b4a8a593d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>e2a89ff7-1380-4c2c-a070-47535ac5686c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Log-out</value>
      <webElementGuid>3a7deb37-7c4d-46a3-937c-72d7f9fc459e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Log-out</value>
      <webElementGuid>767e3941-46d5-4d8b-a8c1-5580414c5d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mxui_widget_VerticalScrollContainer_0&quot;)/div[@class=&quot;mx-scrollcontainer-top region-topbar&quot;]/div[@class=&quot;mx-scrollcontainer-wrapper&quot;]/div[@class=&quot;mx-layoutgrid mx-layoutgrid-fluid container-fluid mx-name-layoutGrid1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-12&quot;]/div[@class=&quot;mx-name-container2 topbar-content&quot;]/div[@class=&quot;navbar navbar-default mx-navbar mx-name-menuBar1 hidden-xs hide-icons&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;mx-navbar-item&quot;]/a[@class=&quot;mx-name-menuBar1-6&quot;]</value>
      <webElementGuid>5f50b45f-6665-40b3-a877-327810fbca6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mxui_widget_VerticalScrollContainer_0']/div/div/div[2]/div/div/div/div[2]/ul/li[7]/a</value>
      <webElementGuid>5fa1963d-16ca-459c-ab7e-a2ddd9f8af55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Log-out')])[2]</value>
      <webElementGuid>6066a67c-a156-4e3e-bdbd-82150bfd9f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Requests'])[1]/preceding::a[1]</value>
      <webElementGuid>a5e53549-c5a7-4c1e-b45c-b55dd21c37a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='akila.k'])[1]/preceding::a[1]</value>
      <webElementGuid>d13757a9-c87b-42d7-944b-be9db0e5f017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[18]</value>
      <webElementGuid>3666e164-07e8-4c37-9255-284242524f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[7]/a</value>
      <webElementGuid>9731515d-8d6a-4e53-a37b-a7c939527523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Log-out' and (text() = ' Log-out' or . = ' Log-out')]</value>
      <webElementGuid>5bd8698a-2dae-4bfa-a590-98f3d91d7405</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
