<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Request time off</name>
   <tag></tag>
   <elementGuidId>dadcdce4-dd52-40f9-8ea1-29a392eed5f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.mx-button.mx-name-actionButton1.btn-lg.btn-block.spacing-outer-bottom-large.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d8d7ec92-8894-4a51-b29f-4a9b465a0728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa53f920-dc78-4d0a-9c25-3500bb26c066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mx-button mx-name-actionButton1 btn-lg btn-block spacing-outer-bottom-large btn-primary</value>
      <webElementGuid>c001b3f3-21cf-40b9-93c0-c475ea2d8e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-id</name>
      <type>Main</type>
      <value>4.LeaveRequest.SNIP_HomeLeft.actionButton1</value>
      <webElementGuid>b51dadf6-05f4-4c01-b998-ef6903f0c60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7fefcc10-3109-4509-8d49-6e43b266898a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Request time off</value>
      <webElementGuid>0d729c62-10c7-40af-a0a7-f02cb6653ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mxui_widget_DataView_4&quot;)/div[@class=&quot;mx-dataview-content&quot;]/div[@class=&quot;mx-layoutgrid mx-layoutgrid-fluid mx-name-layoutGrid7 card spacing-inner-right-medium spacing-inner-left-medium spacing-inner-top-medium spacing-inner-bottom-medium&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-auto col-md col&quot;]/button[@class=&quot;btn mx-button mx-name-actionButton1 btn-lg btn-block spacing-outer-bottom-large btn-primary&quot;]</value>
      <webElementGuid>31edbe4e-4bf8-4234-a428-a69244bda668</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>505ff48e-9115-45c1-9553-80fe5192a107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mxui_widget_DataView_4']/div/div/div/div/button</value>
      <webElementGuid>97a15d7c-b378-40d4-981a-9a7ed97422a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spent PTO'])[1]/following::button[1]</value>
      <webElementGuid>54bda2d1-021b-4c2a-9b0c-93ed9546ebc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='akila.k'])[1]/following::button[1]</value>
      <webElementGuid>d1334d0c-0c74-4e69-a427-8f70ad36c8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Who', &quot;'&quot;, 's out today')])[1]/preceding::button[1]</value>
      <webElementGuid>e76941fc-bb63-4dbe-b3b1-81e2b3f0688d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public holidays'])[1]/preceding::button[1]</value>
      <webElementGuid>17f66a2a-2eea-49e0-9051-13ea847dea16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Request time off']/parent::*</value>
      <webElementGuid>b6a19580-6272-4497-8cbd-9fb59b4c83c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/button</value>
      <webElementGuid>36c4bec7-76ca-40c0-a24d-2e4ea67c1ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Request time off' or . = ' Request time off')]</value>
      <webElementGuid>dc5403ae-ab81-444c-aa9e-f5bb21aa15a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
