<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Leave Requests</name>
   <tag></tag>
   <elementGuidId>990cd001-49b1-471d-8c6d-7c46efcedf6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.mx-text.mx-name-text6.card-title.text-white.text-normal.pull-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mxui_widget_VerticalScrollContainer_0']/div[2]/div/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>8c0ff870-78eb-48a3-91ec-8af42945e999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-text mx-name-text6 card-title text-white text-normal pull-left</value>
      <webElementGuid>06bd1caf-d463-42f3-8754-dd8110e34bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leave Requests</value>
      <webElementGuid>06845641-fc74-4255-9ea8-3c5a50b60dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mxui_widget_VerticalScrollContainer_0&quot;)/div[@class=&quot;mx-scrollcontainer-middle region-content&quot;]/div[@class=&quot;mx-scrollcontainer-wrapper&quot;]/div[@class=&quot;mx-placeholder&quot;]/div[@class=&quot;mx-name-container2 headerhero text-center col-center spacing-outer-bottom-large&quot;]/div[@class=&quot;mx-name-container5 card-overlay&quot;]/h1[@class=&quot;mx-text mx-name-text6 card-title text-white text-normal pull-left&quot;]</value>
      <webElementGuid>bc93fd21-8b66-4c6a-8d9f-721a03b1c315</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mxui_widget_VerticalScrollContainer_0']/div[2]/div/div/div/div/h1</value>
      <webElementGuid>7e08432d-0a8e-458d-aba8-2f099bf9a264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='akila.k'])[1]/preceding::h1[1]</value>
      <webElementGuid>a40bcfa8-f4ab-4d06-847c-7be137dbea98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spent PTO'])[1]/preceding::h1[1]</value>
      <webElementGuid>f5f6729d-88ec-4204-9de1-5e2616293c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Leave Requests']/parent::*</value>
      <webElementGuid>53c3ec3a-6a0c-4346-8844-094e9499d6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>e19727c3-2c86-4dd5-bd5b-03211955b673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Leave Requests' or . = 'Leave Requests')]</value>
      <webElementGuid>f1f28d05-fba9-4dfa-83fe-ccaa2f88856f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
