<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pending</name>
   <tag></tag>
   <elementGuidId>1212e4b5-2fde-4335-b449-06c111c33268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.widget-badge.label.mx-name-badge11.label-warning</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mxui_widget_DataView_8']/div/div/div/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7872b255-83e0-406d-a64f-8cc226b06b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>widget-badge label mx-name-badge11 label-warning</value>
      <webElementGuid>c5a2536e-f4f8-4186-8fe8-e895aa253f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pending</value>
      <webElementGuid>a0dc2651-8bf2-4111-9d66-b2c7cef70ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mxui_widget_DataView_8&quot;)/div[@class=&quot;mx-dataview-content&quot;]/div[@class=&quot;mx-name-container3 card spacing-outer-bottom-large&quot;]/div[@class=&quot;mx-name-layoutGrid4 mx-layoutgrid mx-layoutgrid-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg col-md col align-self-center&quot;]/span[@class=&quot;widget-badge label mx-name-badge11 label-warning&quot;]</value>
      <webElementGuid>bb986f48-9bb2-4331-9a02-09b2f61d97cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mxui_widget_DataView_8']/div/div/div/div/div[2]/span</value>
      <webElementGuid>0397eb99-6c87-47a8-a5cf-89e83121c75a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On Wed 17 Aug 2022'])[1]/following::span[1]</value>
      <webElementGuid>5cee10d3-e8a8-4d7e-a91e-cb16c141e783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sick leave'])[1]/following::span[2]</value>
      <webElementGuid>20c24d9a-e0bf-400c-b9e7-c18c5438b692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team time off this week'])[1]/preceding::span[1]</value>
      <webElementGuid>ad56279c-939a-428e-b611-c46a85312b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No items found'])[1]/preceding::span[1]</value>
      <webElementGuid>db686ab7-b28f-4f60-9511-4819f84462bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pending']/parent::*</value>
      <webElementGuid>8acbc853-ab9d-4ff3-98d4-1c0f211568ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>23518662-77e4-4801-b276-37cef7ec0e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pending' or . = 'Pending')]</value>
      <webElementGuid>2cc141bd-8c89-4ac9-ade4-4846f9262176</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
